services:
  deno-app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DENO_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/hono
      - PORT=8000
    command: ["deno", "run", "--watch", "--allow-net", "main.ts"]
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hono
    ports:
      - "5432:5432"
